[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "wgd v2"
authors = [{name = "Hengchi Chen", email = "hengchichen11@gmail.com"}]
dynamic = ["version", "description"]
